# Generated by Django 4.2.3 on 2023-09-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest_Test',
            new_name='ContestTest',
        ),
    ]
