# Generated by Django 4.2.3 on 2023-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_rename_contest_test_contesttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttest',
            name='input',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Ввод (список через запятую, ; - несколько значений)'),
        ),
    ]
