# Generated by Django 4.2.3 on 2023-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_usercontestanswer_time_alter_contesttest_answer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttest',
            name='input_type',
        ),
        migrations.AlterField(
            model_name='contesttest',
            name='input',
            field=models.TextField(blank=True, verbose_name='Ввод'),
        ),
    ]
