# Generated by Django 4.2.3 on 2023-10-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_remove_contesttest_input_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttest',
            name='answer_type',
        ),
    ]
