# Generated by Django 4.2.3 on 2023-10-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_remove_contesttest_answer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontestanswer',
            old_name='status',
            new_name='short_status',
        ),
        migrations.AddField(
            model_name='usercontestanswer',
            name='big_status',
            field=models.TextField(default='OK', verbose_name='Развёрнутый статус'),
        ),
    ]
