# Generated by Django 4.2.3 on 2023-10-06 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0009_rename_status_usercontestanswer_short_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='for_everyone',
            field=models.BooleanField(default=True, verbose_name='Публичный ли контест:'),
        ),
        migrations.AddField(
            model_name='contest',
            name='special_for_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='contest', to=settings.AUTH_USER_MODEL, verbose_name='Если приватный, то для кого:'),
        ),
    ]
