# Generated by Django 4.2.3 on 2023-10-07 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0010_contest_for_everyone_contest_special_for_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='special_for_users',
            field=models.ManyToManyField(blank=True, related_name='contest', to=settings.AUTH_USER_MODEL, verbose_name='Если приватный, то для кого:'),
        ),
    ]
