# Generated by Django 4.2.3 on 2023-10-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_alter_usercontestanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entered_data',
            field=models.TextField(blank=True, verbose_name='Входные данные'),
        ),
        migrations.AddField(
            model_name='contest',
            name='output_data',
            field=models.TextField(null=True, verbose_name='Входные данные'),
        ),
    ]
