# Generated by Django 4.2.3 on 2023-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_contest_entered_data_contest_output_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='entered_data',
        ),
        migrations.AddField(
            model_name='contest',
            name='input_data',
            field=models.TextField(blank=True, verbose_name='Входные данные (описание)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='output_data',
            field=models.TextField(null=True, verbose_name='Результат (описание)'),
        ),
    ]
