# Generated by Django 4.2.3 on 2023-10-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_alter_contest_input_data_alter_contesttest_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttest',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
