# Generated by Django 4.2.6 on 2023-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_alter_contesttest_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='timeout',
            field=models.IntegerField(default=3, verbose_name='Ограничение по времени в сек.'),
        ),
    ]
