# Generated by Django 4.2.6 on 2023-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_contest_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttest',
            name='type_programm',
            field=models.CharField(choices=[('module', 'Функция'), ('programm', 'Программа')], default='module', max_length=100, verbose_name='Тип программы'),
        ),
        migrations.AlterField(
            model_name='contesttest',
            name='input',
            field=models.TextField(blank=True, null=True, verbose_name='Ввод (если это функция, то с названием)'),
        ),
    ]
