# Generated by Django 4.2.6 on 2023-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_contesttest_type_programm_alter_contesttest_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contesttest',
            name='type_programm',
        ),
        migrations.AddField(
            model_name='contest',
            name='type_programm',
            field=models.CharField(choices=[('module', 'Функция'), ('programm', 'Программа')], default='module', max_length=100, verbose_name='Тип программы'),
        ),
    ]
