# Generated by Django 4.2.6 on 2023-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_remove_contesttest_type_programm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text_to_users', models.TextField(default='Удачи:)', verbose_name='Напутственное слово:')),
                ('contests', models.ManyToManyField(blank=True, to='contest.contest', verbose_name='Задания')),
            ],
        ),
    ]
