# Generated by Django 4.2.6 on 2023-11-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_contestgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='contestgroup',
            options={'verbose_name': 'Группа заданий', 'verbose_name_plural': 'Группы заданий'},
        ),
        migrations.AlterModelOptions(
            name='contesttest',
            options={'verbose_name': 'Тест для задания', 'verbose_name_plural': 'Тесты для задания'},
        ),
        migrations.AlterModelOptions(
            name='usercontestanswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователя'},
        ),
        migrations.AlterField(
            model_name='contestgroup',
            name='text_to_users',
            field=models.TextField(default='Не переживай! Удачи)', verbose_name='Напутственное слово:'),
        ),
    ]
