# Generated by Django 4.2.6 on 2023-11-09 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0021_alter_contest_options_alter_contestgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestgroup',
            name='special_for_users',
            field=models.ManyToManyField(blank=True, related_name='can_view_group', to=settings.AUTH_USER_MODEL, verbose_name='Для кого:'),
        ),
    ]
